# -*- coding: utf-8 -*-
"""Deep-RNNs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8TSY1X-LFoWtFg_-K1fiYs1ZbCXcx68
"""

from tensorflow.keras.datasets import imdb
from keras.models import Sequential
from keras.layers import *
import keras

(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000) # The vocab is now 10k, the revies still 25k

from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(X_train,maxlen=500)
X_test = pad_sequences(X_test,maxlen=500)



model = Sequential()
model.add(Embedding(10000,60))
model.add(SimpleRNN(64,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(64))

model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_split=0.2,batch_size=32)

